name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # This command allows us to run the Action manually from the Actions tab.

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on.

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE so your job can access it.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generates the snake GIF and SVG using the Platane/snk action.
      - name: Generate Snake GIF
        uses: Platane/snk@master
        with:
          github_user_name: Subhadip956425
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the repository for debugging purposes.
      - name: Show repository status
        run: git status

      # Push the changes to the repository.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy the generated files to GitHub Pages from the output branch.
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
